-- Tablas EMPLE y DEPART
-- 01
SELECT  APELLIDO, OFICIO  
	FROM  EMPLE
	WHERE  APELLIDO LIKE 'A%' 
		AND OFICIO LIKE '%E%';
-- 02
SELECT apellido, oficio, loc
  FROM EMPLE E, DEPART D
  WHERE E.dept_no = D.dept_no
	AND oficio = 'ANALISTA';
-- 03
SELECT apellido, oficio, salario, fecha_alt
	FROM emple
	WHERE OFICIO = (SELECT oficio FROM emple WHERE apellido ='JIMENEZ')
		OR salario >= (SELECT salario FROM emple WHERE apellido ='FERNANDEZ');
-- 04
SELECT apellido, oficio, salario 
	FROM emple
	WHERE (dept_no, salario) IN
		(SELECT dept_no, salario FROM emple WHERE apellido ='FERNANDEZ');
-- 05
SELECT  APELLIDO, OFICIO 
	FROM emple
	WHERE OFICIO = (SELECT OFICIO FROM emple  WHERE  APELLIDO = 'JIMENEZ');
-- Tabla LIBRERIA
-- 01
SELECT * 
	FROM LIBRERIA 
	WHERE EJEMPLARES BETWEEN 8 AND 15;
-- 02
SELECT * 
	FROM LIBRERIA 
	WHERE ESTANTE NOT BETWEEN 'B' AND 'D';
-- 03
SELECT TEMA 
	FROM LIBRERIA 
	WHERE EJEMPLARES < 	(SELECT EJEMPLARES FROM LIBRERIA WHERE TEMA LIKE 'Medicina%');
-- 04
SELECT TEMA 
	FROM LIBRERIA 
	WHERE EJEMPLARES NOT BETWEEN 15 AND 20;
-- Tablas ALUMNOS, ASIGNATURAS, y NOTAS
-- 01
SELECT NOMBRE 
	FROM ASIGNATURAS A, ALUMNOS AL, NOTAS N
	WHERE NOMBRE LIKE '%o%o%o%'
		AND POBLA='Madrid' 
		AND A.COD=N.COD 
		AND N.DNI=AL.DNI;
-- 02
SELECT APENOM 
	FROM ALUMNOS AL,ASIGNATURAS A, NOTAS N
	WHERE NOTA BETWEEN 7 AND 8
		AND NOMBRE LIKE 'FOL' 
		AND A.COD=N.COD 
		AND N.DNI=AL.DNI;
-- 03
SELECT APENOM 
	FROM ALUMNOS A, NOTAS N
	WHERE POBLA LIKE 'Madrid'
		and NOTA<5 
		and N.DNI=A.dni;
-- 04
SELECT NOMBRE 
	FROM ASIGNATURAS
	WHERE COD IN (SELECT COD FROM NOTAS WHERE NOTA>=5)
		AND COD NOT IN (SELECT COD FROM NOTAS WHERE NOTA<5);
-- 05
SELECT DISTINCT APENOM 
	FROM ALUMNOS AL, NOTAS N
	WHERE NOTA = (SELECT NOTA FROM NOTAS
					WHERE DNI =(SELECT DNI FROM ALUMNOS WHERE APENOM ='Diaz Fernandez, Maria')
					AND COD=(SELECT COD FROM ASIGNATURAS WHERE NOMBRE ='FOL')
					)
		AND N.DNI=AL.DNI;
