-- 1º) 
SQL> INSERT INTO ALUM
	(SELECT * FROM NUEVOS MINUS SELECT * FROM ALUM);

2 filas creadas.

-- 2º) 
SQL> DELETE FROM ALUM
		WHERE NOMBRE IN
		(SELECT NOMBRE FROM ANTIGUOS);

2 filas borradas.

TABLAS EMPLE y DEPART:

-- 3º) 
 SQL> INSERT INTO EMPLE 
		SELECT 2000, 'SAAVEDRA', OFICIO, DIR, SYSDATE, SALARIO+SALARIO*0.2,COMISION, DEPT_NO
		FROM EMPLE
		WHERE APELLIDO='SALA';

1 fila creada.

-- 4º) 
SQL> UPDATE EMPLE
		SET DEPT_NO=
		(SELECT DEPT_NO FROM EMPLE WHERE OFICIO='EMPLEADO'
		GROUP BY DEPT_NO
		HAVING COUNT(*) = (SELECT MAX(COUNT(*)) FROM EMPLE
						WHERE OFICIO='EMPLEADO'
						GROUP BY DEPT_NO))
		WHERE APELLIDO ='SAAVEDRA';

1 fila actualizada.

-- 5º)  
SQL>  DELETE FROM DEPART
		WHERE DEPT_NO IN
		(SELECT DEPT_NO FROM DEPART
			MINUS
		SELECT DEPT_NO FROM EMPLE);

1 fila borrada.

-- 6º)
SQL> UPDATE CENTROS
		SET NUM_PLAZAS=NUM_PLAZAS/2
		WHERE COD_CENTRO IN
		(SELECT COD_CENTRO 
		FROM PROFESORES 
		GROUP BY COD_CENTRO
		HAVING COUNT(*) < 2);

2 filas actualizadas.

-- 7º)
SQL> DELETE CENTROS
		WHERE COD_CENTRO IN
		(SELECT COD_CENTRO FROM CENTROS 
			MINUS 
		SELECT COD_CENTRO FROM PERSONAL);

1 fila borrada.

-- 8º)
SQL> INSERT INTO PROFESORES
	SELECT DISTINCT cod_centro, 8790055,'Salas, Clara', 'IDIOMA'
	FROM PERSONAL
	WHERE COD_CENTRO IN
	(SELECT COD_CENTRO 
		FROM PERSONAL 
		WHERE FUNCION='ADMINISTRATIVO' 
		GROUP BY COD_CENTRO
		HAVING COUNT(*) = 1);

2 filas creadas.

-- 9º)
SQL> DELETE PERSONAL
		WHERE COD_CENTRO IN
		(SELECT COD_CENTRO FROM CENTROS WHERE NUM_PLAZAS<300)
		AND COD_CENTRO IN
		(SELECT COD_CENTRO FROM PROFESORES GROUP BY COD_CENTRO HAVING COUNT(*) < 2);

2 filas borradas.

-- 10º)
SQL> DELETE PROFESORES
		WHERE DNI NOT IN (SELECT DNI FROM PERSONAL);

1 fila borrada.
